name: Validate

on:
  push:
  pull_request:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658 # master

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: HACS validation
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: integration
